/**
 * Author: Professor Krasso, Marshall Huckins and Rachel White
 * Date: 7 August 2024
 * File: app.js
 * Description: Application setup. Autogenerated using Express generator.
 */

// require statements
const express = require('express');
const createError = require('http-errors');
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const mongoose = require('mongoose');
const { notFoundHandler, errorHandler } = require('./error-handler');

const indexRouter = require('./routes/index');
const taskRouter = require('./routes/tasks');
const projectRouter = require('./routes/projects');

const app = express();

// Only connect to MongoDB when this file is run directly
if (require.main === module) {
  const mongoURI = 'mongodb+srv://web335Admin:Password01@tms-cluster.ebh5hd3.mongodb.net/tms?retryWrites=true&w=majority&appName=tms-cluster';

  mongoose.connect(mongoURI)
    .then(() => console.log('MongoDB connected successfully.'))
    .catch(err => console.error('MongoDB connection error:', err));
}

// CORS middleware with preflight OPTIONS handling
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*'); // allow all origins
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});

// Standard Express middleware
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Route definitions
app.use('/api', indexRouter);
app.use('/api/task', taskRouter);
app.use('/api/project', projectRouter);

// Error handling middleware
app.use(notFoundHandler);
app.use(errorHandler);

module.exports = app;
